---
mainfont: Nunito
font: Nunito
fontsize: 14 pt
output:
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: header.tex
    keep_tex: false
params: 
  file_path: data
  school_name: x
  set_title: x
  teacher_name: x
geometry: "left=1in,right=1in,top=1in,bottom=0.6in"
---


```{r rmarkdown-setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(dev = "cairo_pdf")
options(knitr.kable.NA = "")
options(kableExtra.latex.load_packages = FALSE)

```


```{r setup, include=FALSE}
source("/Volumes/GoogleDrive/My\ Drive/xSEL\ Labs/Scripts/Dashboards/flexdashboard/functions/EE/plot_change_over_time_ee_function_pdf.R")
  
#make datasets of overlapping students if a classrom completed SELweb at both points

#if sufficient number of students took SELweb at both timepoints
common_students <- intersect(district$StudentID, district_time2$StudentID)

class_common_1 <- district[(district$StudentID %in% common_students & 
                               district$TeacherLast== params$teacher_name & 
                               district$School== params$school_name),]


```

## Change Over Time Plot 
```{r summary-plot, echo = FALSE, warning = FALSE, results = "asis"}

if(dim(class_for_plotting_1)[1] >= 10 & dim(class_for_plotting_2)[1] >= 10){
  
  class_for_plotting_1 <- class_for_plotting_1 %>% 
  mutate(Timepoint = "Fall")

  class_for_plotting_2 <- class_for_plotting_2 %>% 
    mutate(Timepoint = "Spring")

  data_class_change <- rbind(class_for_plotting_1, class_for_plotting_2)
   
  plot_change_over_time_ee_pdf(data_class_change, params$teacher_name, dim(class_common_1)[1])
} else {
  
  print("Not enough data collected at both time points (need at least 10 data points for both Fall and Spring)")
  

}

cat(' \n\n\n\n')
cat("  \n")  
```
Above average: $\geq$ 115; At or around average: 90-114; Below average: 70-89; Well below average: $\leq$ 69


## Summary Table for Classroom: Timepoint 1 vs Timepoint 2
```{r summary-table, warning = FALSE, echo = FALSE, results = "asis"}

if(dim(teacher_1)[1] >= 10 & dim(teacher_2)[1] >= 10){

merged_student_links_pdf <- left_join(student_data_for_table, student_data_for_table_2, by = c("Student ID")) %>% 
  rename(LastName = "Last Name.x") %>% 
  arrange(LastName) %>% 
  select("Student ID", "First Name" = "First Name.x", "Last Name" = LastName, Fall = "Overall.x", Spring = "Overall.y",
         Fall = "Emotion Recognition.x", Spring = "Emotion Recognition.y", Fall = "Social Perspective-Taking.x",
         Spring = "Social Perspective-Taking.y", Fall = "Social Problem-Solving.x", Spring = "Social Problem-Solving.y",
         Fall = "Self Control.x", Spring = "Self Control.y") %>% 
  replace(is.na(.), "") 


### Summary Scores by School
kable(merged_student_links_pdf, "latex", booktabs = T, align = "lcllccccccccc", linesep = "") %>% 
  kable_styling(latex_options = c("striped", "bordered"), full_width = F) %>% 
  add_header_above(c("", "", "", "Overall" = 2, "Emotion \nRecognition" = 2, "Social \nPerspective-\nTaking" = 2,
                     "Social \nProblem-\nSolving" = 2, "Self Control" = 2)) %>% 
  column_spec(2:3, width = "1.7cm") %>% 
  column_spec(4:13, width = "0.8cm")

} else {
  print("Not enough data collected at both time points (need at least 10 data points for both Fall and Spring)")
  
}

cat('\n\n\n\n')

```
