


Timepoint 2  {data-icon="fa-table"}
=====================================  

Row
-----------------------------------------------------------------------
### Numbers of students who completed SELweb

```{r}
valueBox(length(district_time2$SEL.SS), icon = "fa-child")
```

### Numbers of schools that administered SELweb

```{r}
#comments <- computeComments()
valueBox(length(unique(district_time2$School)), icon = "fa-building")
```


Row {data-height=500, .tabset .tabset-fade}
-----------------------------------------------------------------------

### Summary Scores by School

```{r}
if(version == "EE"){
  make_summary_table(school_links_2, district_name)
} else if(version == "LE"){
  make_summary_table_le(school_links_2, district_name)
}

```


### Summary Plot for District

```{r}

n_district_time2 <- dim(district_time2)[1]

make_summary_plot(data_for_plotting_2, district_name, n_district_time2)

```

```{r, echo = F, results='asis'}

if(params$student_data == TRUE) {
  cat(paste0('\n### Student-level data', '\n'))
}
```


```{r}


#prep data for student-level table (with links to individual student reports)
if(version == "EE"){
  student_links_district_2 <- make_student_links_district_pdf(district_time2, 2)
  make_student_level_table_links(student_links_district_2)
} else if(version == "LE"){
  student_links_district_2 <- make_student_links_district_pdf_le(district_time2, 2)
  make_student_level_table_links_le(student_links_district_2)
}
```

### PDF report
```{r}
xfun::embed_file(pdf_district_2)
```


Change Over Time {data-icon="fa-bar-chart"}
=====================================  

Row {data-height=650, .tabset .tabset-fade}
-----------------------------------------------------------------------

### District-level
```{r}

common_students <- intersect(district$StudentID, district_time2$StudentID)

#common <- district_time2[(district_time2$StudentID %in% district$StudentID),]

district_common_1 <- district[(district$StudentID %in% common_students),]
district_common_2 <- district_time2[(district_time2$StudentID %in% common_students),]

if(version == "EE"){
  district_time1_plotting <- transform_for_plotting(district_common_1)
  district_time2_plotting <- transform_for_plotting(district_common_2)
} else if(version== "LE"){
  district_time1_plotting <- transform_for_plotting_le(district_common_1)
  district_time2_plotting <- transform_for_plotting_le(district_common_2)
}


data_for_plotting_change_1 <- district_time1_plotting %>% 
  mutate(Timepoint = "Fall")

data_for_plotting_change_2 <- district_time2_plotting %>% 
  mutate(Timepoint = "Spring")

data_for_plotting_change <- rbind(data_for_plotting_change_1, data_for_plotting_change_2)

if(version == "EE"){
  plot_change_over_time_ee(data_for_plotting_change, district_name, dim(district_common_2)[1])
} else if(version == "LE"){
  plot_change_over_time_le(data_for_plotting_change, district_name, dim(district_common_2)[1])
}



```

### PDF report
```{r}
xfun::embed_file(pdf_district_change)

```

